// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type IdentifiedPerson struct {
	Identified  bool   `json:"identified"`
	HasPassword bool   `json:"hasPassword"`
	AuthKey     string `json:"authKey"`
}

type ReqAuthPerson struct {
	AuthKey  *string `json:"authKey"`
	Key      *string `json:"key"`
	Password *string `json:"password"`
}
