// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type IdentifiedPerson struct {
	Idented     bool   `json:"idented"`
	HasPassword bool   `json:"hasPassword"`
	AuthKey     string `json:"authKey"`
}

type Person struct {
	UID     string `json:"uid"`
	Name    string `json:"name"`
	Country string `json:"country"`
	Phone   string `json:"phone"`
	Token   string `json:"token"`
}

type ReqAuthPerson struct {
	AuthKey  *string `json:"authKey"`
	Key      *string `json:"key"`
	Password *string `json:"password"`
}
